sonar.projectKey=gausshj_taskChamber
sonar.organization=gausshj

sonar.sources=taskchamber
sonar.tests=tests

sonar.python.version=3.11, 3.12, 3.13, 3.14
sonar.python.coverage.reportPaths=coverage.xml
